### ISSUE TITLE
Timetable

### ISSUE THREAD

**Issue by xiaoer666** [nyaggah/bedframe#252]
Bro, this is a very nice job, but can I give a timetable, when will it be completed?

**Comment by JoeyDoey** [comment]
Thanks, @xiaoer666 !

Still doing the initial build out so that ultimately you can build extensions in any of the languages/templates Vite supports i.e.:

<img width="369" alt="image" src="https://github.com/nyaggah/bedframe/assets/284415/ec067cb5-9e94-48f5-a285-14ada73ef0fa">

^^^ [Vite template presets](https://vitejs.dev/guide/#trying-vite-online)

Currently you can build with react (w/ typescript + tailwind or styled components). Should already be able to get pretty far.

What feature are you looking to see finished/ prioritized?
