### ISSUE TITLE
Can't find dev server on safari 

### ISSUE THREAD

**Issue by MalikElate** [nyaggah/bedframe#542]
Hi I created a new bedframe project. After running converting to safari, running in xcode, running npm run dev safari, I can't open the extension settings 

<img width="764" alt="Screenshot 2024-08-31 at 9 43 36 AM" src="https://github.com/user-attachments/assets/b3c7cd98-fc61-4555-a79a-90e08404abe4">

Did a miss a set up step?

**Comment by JoeyDoey** [comment]
Hi @MalikElate Thanks for checking out Bedframe! No, I don't think you missed a step. 

It's just not how the Safari Web Extension dev process works. I'm not sure (right now) its going to be possible to dev for Safari like you would the Chromium-based and Firefox browsers.

Using the `convert:safari` package.json script, the packaged `/dist/safari` output _is_ being referenced in the XCode project but since you actually have to package (aka compile) the extension and install it for Safari, I don't think the traditional JS dev process (with Vite's HMR/ live reloading) is going to be possible there.
<img width="701" alt="image" src="https://github.com/user-attachments/assets/c61d46ed-9fcd-4e2f-9b78-9f581720895e">


In case I'm wrong, peruse the official [Developing a Safari Web Extension](https://developer.apple.com/documentation/safariservices/developing-a-safari-web-extension) docs and see if you find any info about it there.

Might also be helpful to check out the [`safari-web-extension-converter`](https://developer.apple.com/documentation/safariservices/converting-a-web-extension-for-safari#Run-the-converter) docs so you can update the `convert:safari` script options if need be
